name: Deploy To-Do App to Heroku

on:
  push:
    branches:
      - main # Or 'master', the branch you push changes to
    paths:
      - 'express/public/to_do_list/**' # Trigger only for changes in this specific subfolder
      - '.github/workflows/deploy-todo-app.yml' # Also trigger if the workflow file itself changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install dependencies (for to-do app)
        run: npm install --prefix express/public/to_do_list # Install dependencies from this subfolder

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_TODO_APP_NAME }} # Your specific Heroku app name secret
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: 'express/public/to_do_list' # Tell Heroku to deploy from this subdirectory
