# This is a new comment to force workflow re-evaluation
name: Dynamic Multi-App Heroku Deploy
# ... rest of your workflow ...


on:
  push:
    branches:
      - main # Or 'master'
    paths:
      - 'homepage-app/**'
      - '.github/workflows/dynamic-deploy.yml'

jobs:
  find_apps: # Job 1: Finds all deployable app directories
    runs-on: ubuntu-latest
    outputs:
      app_dirs_json: ${{ steps.scan.outputs.app_dirs_json }}
    env:
      APP_BASE_DIRS: "homepage-app" # The top-level folder where your apps are

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq (for package.json parsing and JSON output)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Scan for Apps
        id: scan
        run: |
          set -e

          ALL_APP_DIRS_ARRAY=()
          echo "Scanning for apps in: $APP_BASE_DIRS"
          for BASE_DIR in $APP_BASE_DIRS; do
            FOUND_DIRS=$(find "$BASE_DIR" -type f -name "package.json" -exec dirname {} \;)
            for DIR in $FOUND_DIRS; do
              ALL_APP_DIRS_ARRAY+=("$DIR")
            done
          done

          UNIQUE_APP_DIRS_NEWLINES=$(printf "%s\n" "${ALL_APP_DIRS_ARRAY[@]}" | sort -u)

          if [ -z "$UNIQUE_APP_DIRS_NEWLINES" ]; then
            echo "No applications found with package.json in '$APP_BASE_DIRS'. Exiting."
            printf "app_dirs_json=[]\n" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Found applications in directories (for debugging):"
          echo "$UNIQUE_APP_DIRS_NEWLINES"

          APP_DIRS_JSON=$(echo "$UNIQUE_APP_DIRS_NEWLINES" | jq -R . | jq -s -c .)
          echo "Generated JSON (single line): $APP_DIRS_JSON"

          printf "app_dirs_json=%s\n" "$APP_DIRS_JSON" >> "$GITHUB_OUTPUT"
        shell: bash

  deploy_each_app: # Job 2: Deploys each app found in the previous job
    needs: find_apps
    runs-on: ubuntu-latest
    if: ${{ needs.find_apps.outputs.app_dirs_json != '[]' }}
    strategy:
      fail-fast: false # Allow other apps to deploy even if one fails
      matrix:
        app_dir: ${{ fromJson(needs.find_apps.outputs.app_dirs_json) }}

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install jq (for package.json parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read App Config and Prepare Deploy Variables
        id: prepare_vars
        run: |
          set -e
          APP_DIR="${{ matrix.app_dir }}"
          APP_FOLDER_NAME=$(basename "$APP_DIR")
          PACKAGE_JSON_APP_NAME=$(jq -r '.name' "$APP_DIR/package.json" || echo "")
          HEROKU_APP_TARGET_NAME=$(jq -r '.herokuAppName' "$APP_DIR/package.json" || echo "")

          # Consistency Check: Folder Name vs. package.json 'name'
          if [ "$APP_FOLDER_NAME" != "$PACKAGE_JSON_APP_NAME" ]; then
            echo "::error::Inconsistency detected for app '${APP_FOLDER_NAME}' (path: '${APP_DIR}'):"
            echo "::error::Folder name ('${APP_FOLDER_NAME}') does NOT match 'name' in package.json ('${PACKAGE_JSON_APP_NAME}')."
            echo "::error::Please **rename either the folder or the 'name' in package.json to match**, then commit and re-run."
            exit 1 # Fail this specific matrix job
          fi

          # Heroku App Name Check
          if [ -z "$HEROKU_APP_TARGET_NAME" ] || [ "$HEROKU_APP_TARGET_NAME" == "null" ]; then
            echo "::error::'herokuAppName' field not found or is empty in '$APP_DIR/package.json'."
            echo "::error::Please add '\"herokuAppName\": \"YOUR_HEROKU_APP_NAME\"' to this package.json file."
            exit 1 # Fail this specific matrix job
          fi
          
          echo "Installing dependencies for ${APP_FOLDER_NAME} (path: '${APP_DIR}')..."
          npm install --prefix "$APP_DIR" || {
              echo "::error::npm install failed for app in '${APP_DIR}'. Deployment failed for this app."
              exit 1 # Fail this specific matrix job
          }

          # Output variables that the subsequent 'uses' step can consume
          echo "heroku_app_name=$HEROKU_APP_TARGET_NAME" >> "$GITHUB_OUTPUT"
          echo "app_folder_name=$APP_FOLDER_NAME" >> "$GITHUB_OUTPUT"

        shell: bash

      - name: Deploy to Heroku - Actual Action
        id: deploy_action
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ steps.prepare_vars.outputs.heroku_app_name }}
          appdir: ${{ matrix.app_dir }}

  generate_app_list_file: # Job 3: Generates apps.md file
    needs: [find_apps, deploy_each_app] 
    runs-on: ubuntu-latest
    if: |
      always() &&
      needs.find_apps.outputs.app_dirs_json != '[]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Checkout the branch we're working on

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate apps.md Content
        id: generate_content
        run: |
          set -e # This ensures script exits on first error

          echo "Generating apps.md content..."
          
          # --- CRITICAL FIX: Ensure APP_DIRS_JSON is correctly retrieved from 'find_apps' job output ---
          # This line MUST fetch the JSON from the previous job using GitHub Actions' context.
          # The problematic hardcoded string "[\"homepage-app\",\"homepage-app/to_do_list\"]"
          # is the source of the `jq` parse error.
          APP_DIRS_JSON="${{ needs.find_apps.outputs.app_dirs_json }}" # <--- This is the ONLY CORRECT LINE for this assignment

          # Handle the case where the JSON might somehow be empty or invalid (though it shouldn't if find_apps succeeded)
          if [ -z "$APP_DIRS_JSON" ] || [ "$APP_DIRS_JSON" == "null" ] || [ "$APP_DIRS_JSON" == "[]" ]; then
              echo "No valid app directories JSON received from find_apps job. Skipping apps.md generation."
              echo "apps_md_section_content=" >> "$GITHUB_OUTPUT"
              echo "apps_md_updated_flag=false" >> "$GITHUB_OUTPUT"
              exit 0 # Exit successfully as no content needs to be generated
          fi

          # Attempt to parse JSON. Use '|| true' to prevent script from exiting if jq fails,
          # allowing the error message to be printed.
          APP_DIRS=$(echo "$APP_DIRS_JSON" | jq -r '.[]' || echo "jq_parse_error") 
          
          if [ "$APP_DIRS" == "jq_parse_error" ]; then
              echo "::error::Failed to parse app directories JSON: '$APP_DIRS_JSON'."
              echo "::error::This indicates an issue with the JSON output from the 'find_apps' job."
              exit 1 # Fail this step if JSON parsing itself fails
          fi
          
          # If APP_DIRS is empty *after* jq, it means the array was empty.
          if [ -z "$APP_DIRS" ]; then 
              echo "No app directories found after JSON parsing. Skipping apps.md content generation."
              echo "apps_md_section_content=" >> "$GITHUB_OUTPUT"
              echo "apps_md_updated_flag=false" >> "$GITHUB_OUTPUT"
              exit 0 # Exit successfully
          fi
          
          APPS_MD_CONTENT="# 🚀 Deployed Applications\n\n"
          APPS_MD_CONTENT+="This file lists the applications deployed from this repository to Heroku.\n\n"
          APPS_MD_CONTENT+="## App List\n\n"
          APPS_UPDATED_FLAG=false # To track if any app details were successfully added
          
          # Iterate through apps and construct content
          for APP_DIR in $APP_DIRS; do
            APP_FOLDER_NAME=$(basename "$APP_DIR")
            
            # Re-read package.json from the checked out repo to get herokuAppName
            HEROKU_APP_TARGET_NAME=$(jq -r '.herokuAppName' "$APP_DIR/package.json" || echo "") 
            
            if [ -z "$HEROKU_APP_TARGET_NAME" ] || [ "$HEROKU_APP_TARGET_NAME" == "null" ]; then
                echo "::warning::Skipping apps.md entry for '${APP_FOLDER_NAME}' as 'herokuAppName' is missing in its package.json."
                continue # Skip this app, but don't fail the whole step
            fi
            
            APP_URL="https://${HEROKU_APP_TARGET_NAME}.herokuapp.com/"
            APPS_MD_CONTENT+="* **${APP_FOLDER_NAME}:** [${APP_URL}](${APP_URL})\n"
            APPS_UPDATED_FLAG=true
          done
          
          # Output the generated content and a flag indicating if there's anything to write
          APPS_MD_CONTENT_ESCAPED=$(echo -e "$APPS_MD_CONTENT" | sed -E ':a;N;$!ba;s/\n/%0A/g;s/\r/%0D/g;s/%/%25/g')
          echo "apps_md_section_content=$APPS_MD_CONTENT_ESCAPED" >> "$GITHUB_OUTPUT"
          echo "apps_md_updated_flag=$APPS_UPDATED_FLAG" >> "$GITHUB_OUTPUT"
        shell: bash
        
      - name: Write apps.md File
        # This step will only run if apps_md_updated_flag is true (meaning content was generated)
        # and the previous 'generate_content' step succeeded.
        if: ${{ steps.generate_content.outputs.apps_md_updated_flag == 'true' }}
        run: |
          # Decode the content
          APPS_MD_SECTION_CONTENT=$(echo "${{ steps.generate_content.outputs.apps_md_section_content }}" | sed 's/%0A/\n/g;s/%0D/\r/g;s/%25/%/g')

          echo "$APPS_MD_SECTION_CONTENT" > apps.md # Write directly to apps.md
        shell: bash

      - name: Commit and Push apps.md
        # This step will only run if apps_md_updated_flag is true (meaning content was generated)
        # and the previous 'Write apps.md File' step succeeded.
        if: ${{ steps.generate_content.outputs.apps_md_updated_flag == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Update deployed app links in apps.md"
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
